
project_id = "irjjksfhyiwsbsipeyrj"

[functions.ai-matching]
verify_jwt = true

[functions.ai-embeddings]
verify_jwt = true

[functions.mobile-api]
verify_jwt = true

[functions.blockchain-verification]
verify_jwt = true

[functions.ar-visualization]
verify_jwt = true

[functions.roi-calculator]
verify_jwt = true

[functions.regulatory-sync]
verify_jwt = true

[functions.anvisa-sync]
verify_jwt = false

[functions.brazilian-regulatory-api]
verify_jwt = false

[functions.anvisa-real-api]
verify_jwt = false

[functions.fda-api]
verify_jwt = false

[functions.ai-matching-enhanced]
verify_jwt = true

[functions.roi-calculator-enhanced]
verify_jwt = true

[functions.system-monitor-enhanced]
verify_jwt = true

[functions.advanced-analytics]
verify_jwt = true

[functions.real-time-alerts]
verify_jwt = true

[functions.report-system]
verify_jwt = true

[functions.pics-api]
verify_jwt = false

[functions.ich-guidelines]
verify_jwt = false

[functions.ema-guidelines]
verify_jwt = false

[functions.who-guidelines]
verify_jwt = false

[functions.perplexity-search]
verify_jwt = true

[functions.anvisa-real-sync]
verify_jwt = false

[functions.fda-real-sync]
verify_jwt = false

[functions.real-time-alerts]
verify_jwt = true

[functions.auto-sync]
verify_jwt = true

[functions.chat-system]
verify_jwt = true

[functions.industrial-segmentation]
verify_jwt = true
