
project_id = "irjjksfhyiwsbsipeyrj"

[functions.regulatory-sync]
verify_jwt = false

[functions.federal-learning-system]
verify_jwt = true

[functions.kb-rag]
verify_jwt = true

[functions.kb-ingest]
verify_jwt = true

[functions.comprehensive-integration-sync]
verify_jwt = false

[functions.brazilian-regulatory-api]
verify_jwt = false

[functions.ai-coordinator-orchestrator]
verify_jwt = true

[functions.ai-project-analyst]
verify_jwt = true

[functions.ai-business-strategist]
verify_jwt = true

[functions.ai-technical-regulatory]
verify_jwt = true

[functions.ai-document-assistant]
verify_jwt = true

[functions.master-chatbot]
verify_jwt = true

[functions.master-automation]
verify_jwt = true
