
project_id = "irjjksfhyiwsbsipeyrj"

[functions.ai-matching]
verify_jwt = true

[functions.ai-embeddings]
verify_jwt = true

[functions.roi-calculator]
verify_jwt = true

[functions.regulatory-sync]
verify_jwt = true

[functions.anvisa-sync]
verify_jwt = false

[functions.brazilian-regulatory-api]
verify_jwt = false

[functions.anvisa-real-api]
verify_jwt = false
