
project_id = "irjjksfhyiwsbsipeyrj"

[api]
enabled = true
port = 54321
schemas = ["public", "graphql_public"]
extra_search_path = ["public", "extensions"]
max_rows = 1000

[auth]
enabled = true
port = 54324
site_url = "https://irjjksfhyiwsbsipeyrj.supabase.co"
additional_redirect_urls = ["https://lovable.dev"]
jwt_expiry = 3600
enable_signup = true
enable_email_confirmations = false
enable_email_change_confirmations = true
enable_phone_confirmations = false
enable_phone_change_confirmations = true

[auth.email]
enable_signup = true
double_confirm_changes = true
enable_confirmations = false
template = {}

[auth.sms]
enable_signup = false
enable_confirmations = false
template = "Your code is {{ .Code }}"

[auth.external.apple]
enabled = false
client_id = ""
secret = ""
redirect_uri = ""

[auth.external.azure]
enabled = false
client_id = ""
secret = ""
redirect_uri = ""

[auth.external.bitbucket]
enabled = false
client_id = ""
secret = ""
redirect_uri = ""

[auth.external.discord]
enabled = false
client_id = ""
secret = ""
redirect_uri = ""

[auth.external.facebook]
enabled = false
client_id = ""
secret = ""
redirect_uri = ""

[auth.external.github]
enabled = false
client_id = ""
secret = ""
redirect_uri = ""

[auth.external.gitlab]
enabled = false
client_id = ""
secret = ""
redirect_uri = ""

[auth.external.google]
enabled = false
client_id = ""
secret = ""
redirect_uri = ""

[auth.external.keycloak]
enabled = false
client_id = ""
secret = ""
redirect_uri = ""

[auth.external.linkedin]
enabled = false
client_id = ""
secret = ""
redirect_uri = ""

[auth.external.notion]
enabled = false
client_id = ""
secret = ""
redirect_uri = ""

[auth.external.twitch]
enabled = false
client_id = ""
secret = ""
redirect_uri = ""

[auth.external.twitter]
enabled = false
client_id = ""
secret = ""
redirect_uri = ""

[auth.external.slack]
enabled = false
client_id = ""
secret = ""
redirect_uri = ""

[auth.external.spotify]
enabled = false
client_id = ""
secret = ""
redirect_uri = ""

[auth.external.workos]
enabled = false
client_id = ""
secret = ""
redirect_uri = ""

[auth.external.zoom]
enabled = false
client_id = ""
secret = ""
redirect_uri = ""

[functions.advanced-analytics]
verify_jwt = true

[functions.advanced-regulatory-matching]
verify_jwt = true

[functions.ai-chatbot]
verify_jwt = false

[functions.ai-embeddings]
verify_jwt = true

[functions.ai-matching]
verify_jwt = true

[functions.ai-matching-enhanced]
verify_jwt = true

[functions.ai-matching-monitor]
verify_jwt = true

[functions.anvisa-real-api]
verify_jwt = false

[functions.anvisa-real-sync]
verify_jwt = false

[functions.anvisa-sync]
verify_jwt = false

[functions.ar-visualization]
verify_jwt = true

[functions.auto-sync]
verify_jwt = false

[functions.blockchain-verification]
verify_jwt = true

[functions.brazilian-regulatory-api]
verify_jwt = false

[functions.chat-system]
verify_jwt = true

[functions.check-subscription]
verify_jwt = true

[functions.comprehensive-integration-sync]
verify_jwt = false

[functions.create-checkout]
verify_jwt = true

[functions.create-test-notification]
verify_jwt = true

[functions.customer-portal]
verify_jwt = true

[functions.ema-guidelines]
verify_jwt = false

[functions.fda-api]
verify_jwt = false

[functions.fda-real-sync]
verify_jwt = false

[functions.ich-guidelines]
verify_jwt = false

[functions.industrial-segmentation]
verify_jwt = true

[functions.ml-feedback-loop]
verify_jwt = true

[functions.mobile-api]
verify_jwt = true

[functions.notification-cleanup]
verify_jwt = false

[functions.perplexity-search]
verify_jwt = true

[functions.pics-api]
verify_jwt = false

[functions.real-integration-sync]
verify_jwt = false

[functions.real-time-alerts]
verify_jwt = true

[functions.regulatory-sync]
verify_jwt = false

[functions.report-system]
verify_jwt = true

[functions.roi-calculator]
verify_jwt = true

[functions.roi-calculator-enhanced]
verify_jwt = true

[functions.sentiment-analysis]
verify_jwt = true

[functions.system-monitor]
verify_jwt = true

[functions.system-monitor-enhanced]
verify_jwt = true

[functions.test-integration]
verify_jwt = false

[functions.two-factor-setup]
verify_jwt = true

[functions.webhook-handler]
verify_jwt = false

[functions.webrtc-signaling]
verify_jwt = true

[functions.who-guidelines]
verify_jwt = false

[functions.master-chatbot]
verify_jwt = true

[functions.ai-business-strategist]
verify_jwt = true

[functions.ai-technical-regulatory]
verify_jwt = true

[functions.ai-document-assistant]
verify_jwt = true

[functions.ai-coordinator-orchestrator]
verify_jwt = true

[db]
port = 54322
major_version = 15

[db.pooler]
enabled = false
port = 54329
pool_mode = "transaction"
default_pool_size = 20
max_client_conn = 100

[realtime]
enabled = true
port = 54323
ip_version = "ipv4"

[studio]
enabled = true
port = 54323
api_url = "http://localhost:54321"

[inbucket]
enabled = true
port = 54324
smtp_port = 54325
pop3_port = 54326

[storage]
enabled = true
port = 54325
file_size_limit = "50MiB"
