
project_id = "irjjksfhyiwsbsipeyrj"

[api]
enabled = true
port = 54321
schemas = ["public", "graphql_public"]
extra_search_path = ["public", "extensions"]
max_rows = 1000

[db]
port = 54322
shadow_port = 54320
major_version = 15

[db.pooler]
enabled = false
port = 54329
pool_mode = "transaction"
default_pool_size = 20
max_client_conn = 100

[realtime]
enabled = true
port = 54323
tenant_id = "realtime-dev"

[studio]
enabled = true
port = 54324
api_url = "http://127.0.0.1:54321"

[inbucket]
enabled = true
port = 54325
smtp_port = 54326
pop3_port = 54327

[storage]
enabled = true
port = 54326
file_size_limit = "50MiB"

[auth]
enabled = true
port = 54321
site_url = "http://127.0.0.1:3000"
additional_redirect_urls = ["https://127.0.0.1:3000"]
jwt_expiry = 3600
enable_signup = true
enable_confirmations = false

[auth.email]
enable_signup = true
double_confirm_changes = true
enable_confirmations = false

# AI Agent Functions
[functions.ai-project-analyst]
verify_jwt = true

[functions.ai-business-strategist]
verify_jwt = true

[functions.ai-technical-regulatory]
verify_jwt = true

[functions.ai-document-assistant]
verify_jwt = true

[functions.ai-coordinator]
verify_jwt = true

[functions.chat-system]
verify_jwt = true

[functions.perplexity-ai]
verify_jwt = true
