
project_id = "irjjksfhyiwsbsipeyrj"

[api]
enabled = true
port = 54321
schemas = ["public", "graphql_public"]
extra_search_path = ["public", "extensions"]
max_rows = 1000

[auth]
enabled = true
port = 54324
site_url = "http://localhost:3000"
additional_redirect_urls = ["https://lovable.dev"]
jwt_expiry = 3600
enable_signup = true
enable_anonymous_sign_ups = false

[edge_functions]
enabled = true

[functions.ai-project-analyst]
verify_jwt = true

[functions.ai-business-strategist]
verify_jwt = true

[functions.ai-technical-regulatory]
verify_jwt = true

[functions.ai-document-assistant]
verify_jwt = true

[functions.ai-coordinator-orchestrator]
verify_jwt = true

[functions.federal-learning-system]
verify_jwt = true

[functions.kb-ingest]
verify_jwt = true

[functions.kb-rag]
verify_jwt = true

[functions.perplexity-search]
verify_jwt = false

[functions.comprehensive-integration-sync]
verify_jwt = false

[realtime]
enabled = true
port = 54323
max_header_length = 4096
